# 应用基础配置
spring:

  # PostgreSQL数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cosmos_im?serverTimezone=Asia/Shanghai
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

  # 邮件服务配置
  mail:
    host: smtp.qq.com
    port: 587
    username: xxxxx@qq.com
    password: xxxxxxxxx
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# MyBatis配置
mybatis:
  # mapper文件位置
  mapper-locations: classpath:mapper/**/*.xml
  #  type-aliases-package: com.qfleaf.package.model
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名转换
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL日志
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: imtoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # jwt秘钥
  jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk

# minio自定义配置
minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin



# swagger文档配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# 日志配置
logging:
  level:
    com.qfleaf: debug
